### ISSUE TITLE
Initial layout for page

### ISSUE THREAD

**Issue by pjlawler** [pjlawler/destination-briefing#1]

**Comment by lwjones** [comment]
`<dataform>` elements are unable to be edited with CSS. [Using dataform elements are described here](https://webdesign.tutsplus.com/tutorials/introducing-the-html5-datalist-element--webdesign-9888).

Suggested remedy for consistent styling: change `dataform` to `select` and [use autocomplete to populate the options with autocomplete.](https://www.w3schools.com/howto/howto_js_autocomplete.asp)

**Comment by pjlawler** [comment]
Looks awesome!
