### ISSUE TITLE
Need to add a copyright info from creator of animated wx icons in the readme

### ISSUE THREAD

**Issue by pjlawler** [pjlawler/destination-briefing#15]
Copyright (c) 2020-2022 Bas Milius

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

**Comment by DanielP1742** [comment]
Done! 

I added link to Bas Milius Animated wx icons GitHub page 
I added link to the license info 
And clearly stated copyright.
